### ISSUE TITLE
Data issues

### ISSUE THREAD

**Issue by SHAOTAO1998** [gomezzz/MSMatch#49]
Can you share the data you used for your experiment?

**Comment by gomezzz** [comment]
Hi @SHAOTAO1998 ,

which data in particular are you referring to? 

Links to all the used dataset are in the paper [here](https://arxiv.org/pdf/2103.10368.pdf) 
i.e.
EuroSAT can be found here https://github.com/phelber/EuroSAT
UCM here http://weegee.vision.ucmerced.edu/datasets/landuse.html

**Comment by SHAOTAO1998** [comment]
Thank you for your help！
I have downloaded the code, the program can not run at present.


The following is an error message：
(f) D:\ST\MSMatch-main&gt;python train.py --dataset eurosat_rgb --net efficientnet-b0
D:\Anaconda3\envs\f\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:572: FutureWarning: In the future `np.object` will be defined as the corresponding NumPy scalar.
&nbsp; (np.object, string),
Traceback (most recent call last):
&nbsp; File "train.py", line 15, in <module&gt;
&nbsp; &nbsp; from utils import net_builder, get_logger, count_parameters, create_dir_str
&nbsp; File "D:\ST\MSMatch-main\utils.py", line 3, in <module&gt;
&nbsp; &nbsp; from torch.utils.tensorboard import SummaryWriter
&nbsp; File "D:\Anaconda3\envs\f\lib\site-packages\tensorboard\plugins\histogram\summary_v2.py", line 38, in <module&gt;
&nbsp; &nbsp; from tensorboard.util import tensor_util
&nbsp; File "D:\Anaconda3\envs\f\lib\site-packages\tensorboard\util\tensor_util.py", line 24, in <module&gt;
&nbsp; &nbsp; from tensorboard.compat.tensorflow_stub import dtypes, compat, tensor_shape
&nbsp; File "D:\Anaconda3\envs\f\lib\site-packages\tensorboard\compat\tensorflow_stub\__init__.py", line 25, in <module&gt;
&nbsp; &nbsp; from .dtypes import as_dtype&nbsp; # noqa
&nbsp; File "D:\Anaconda3\envs\f\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py", line 572, in <module&gt;
&nbsp; &nbsp; (np.object, string),
&nbsp; File "D:\Anaconda3\envs\f\lib\site-packages\numpy\__init__.py", line 305, in __getattr__
&nbsp; &nbsp; raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'object'.
`np.object` was a deprecated alias for the builtin `object`. To avoid this error in existing code, use `object` by itself. Doing this will not modify any behavior and is safe.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
&nbsp; &nbsp; https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations







------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gomezzz/MSMatch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月18日(星期一) 晚上8:36
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gomezzz/MSMatch] Data issues (Issue #49)





 
Hi @SHAOTAO1998 ,
 
which data in particular are you referring to?
 
Links to all the used dataset are in the paper here
 i.e.
 EuroSAT can be found here https://github.com/phelber/EuroSAT
 UCM here http://weegee.vision.ucmerced.edu/datasets/landuse.html

**Comment by gomezzz** [comment]
@SHAOTAO1998 did you follow there installation instructions here? https://github.com/gomezzz/MSMatch/tree/main#installation

From the error messages it seems as if you have a non-compatible numpy version (in the provided environment it is fixed to 1.23.4.

**Comment by SHAOTAO1998** [comment]
The problem has been solved.




Torch does not need to download a GPU-specific version？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gomezzz/MSMatch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月19日(星期二) 晚上6:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gomezzz/MSMatch] Data issues (Issue #49)





 
@SHAOTAO1998 did you follow there installation instructions here? https://github.com/gomezzz/MSMatch/tree/main#installation
 
From the error messages it seems as if you have a non-compatible numpy version (in the provided environment it is fixed to 1.23.4.

**Comment by gomezzz** [comment]
> The problem has been solved.

Good to hear! I will close this then, feel free to re-open in case of problems.

> Torch does not need to download a GPU-specific version？

I think this has changed at some points, I am not sure, not an expert on it. If the training is very slow, you may have to consult the pytorch docs / try installing additional packages.

**Comment by SHAOTAO1998** [comment]
At present, this problem has arisen, I am not sure why？


&nbsp; &nbsp; if args.rank % ngpus_per_node == 0:
ZeroDivisionError: integer division or modulo by zero&nbsp; &nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gomezzz/MSMatch"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年12月19日(星期二) 晚上7:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gomezzz/MSMatch] Data issues (Issue #49)





  
The problem has been solved.
  
Good to hear! I will close this then, feel free to re-open in case of problems.
  
Torch does not need to download a GPU-specific version？
  
I think this has changed at some points, I am not sure, not an expert on it. If the training is very slow, you may have to consult the pytorch docs / try installing additional packages.
